name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PI_SSH_HOST }}
          username: ${{ secrets.PI_SSH_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd ${{ secrets.PI_PROJECT_PATH }}
            git pull origin main
            npm ci
            npm run build
            pm2 restart ${{ secrets.PI_PM2_NAME }}